
let items = [
  {
    id: 1,
    img: "/images/shoes1.webp",
    title: "Red Nike Runner",
    desc: "Comfortable, stylish running shoes for everyday use.",
    quantity: 1,
    price: 1000,
    category: "Mens",
  },
  {
    id: 2,
    img: "/images/saree1.webp",
    title: "Elegant Black Saree",
    desc: "Beautiful black saree with a modern touch for special occasions.",
    quantity: 1,
    price: 2000,
    category: "Women",
  },
  {
    id: 3,
    img: "/images/tshirt2.webp",
    title: "White Casual T-Shirt",
    desc: "Soft and comfortable t-shirt for a relaxed look.",
    quantity: 1,
    price: 500,
    category: "Mens",
  },
  {
    id: 4,
    img: "/images/tshirt1.webp",
    title: "Blue Marathon Pro Shoes",
    desc: "Designed for marathon runners with extra cushioning.",
    quantity: 1,
    price: 1200,
    category: "Mens",
  },
  {
    id: 5,
    img: "/images/jeans.webp",
    title: "Stylish Blue Jeans",
    desc: "Trendy and comfortable jeans perfect for any occasion.",
    quantity: 1,
    price: 1300,
    category: "Mens",
  },
  {
    id: 6,
    img: "/images/saree2.webp",
    title: "Graceful Pink Saree",
    desc: "Elegant saree with beautiful patterns for festive events.",
    quantity: 1,
    price: 2500,
    category: "Women",
  },
  {
    id: 7,
    img: "/images/bag1.webp",
    title: "Leather Handbag",
    desc: "Premium quality handbag with spacious compartments.",
    quantity: 1,
    price: 2200,
    category: "Women",
  },
  {
    id: 8,
    img: "/images/jwellary.webp",
    title: "Elegant Gold Necklace",
    desc: "Beautifully designed gold-plated necklace for a royal look.",
    quantity: 1,
    price: 5000,
    category: "Women",
  },
  {
    id: 9,
    img: "/images/bat.webp",
    title: "Cricket Bat - Pro Edition",
    desc: "High-quality wooden bat for professional cricket players.",
    quantity: 1,
    price: 1800,
    category: "Sports, Books & More",
  },
  {
    id: 10,
    img: "/images/football.webp",
    title: "Official Size Football",
    desc: "Durable and high-performance football for all surfaces.",
    quantity: 1,
    price: 1200,
    category: "Sports, Books & More",
  },
  {
    id: 11,
    img: "/images/book.webp",
    title: "Atomic Habits",
    desc: "A must-read book for self-improvement and habit formation.",
    quantity: 1,
    price: 400,
    category: "Sports, Books & More",
  },
  {
    id: 12,
    img: "/images/book2.webp",
    title: "Psychology of Money",
    desc: "A deep dive into how people think about money and wealth.",
    quantity: 1,
    price: 500,
    category: "Sports, Books & More",
  },
  {
    id: 13,
    img: "/images/hero-image.png",
    title: "Red Nike Runner",
    desc: "Comfortable, stylish running shoes for everyday use.",
    quantity: 1,
    price: 1000,
    category: "Mens",
  }
];

export default items;
